##################################################################################
# Cloudify AWS EC2 built in types and plugins definitions.
##################################################################################

plugins:
  bmc:
    executor: central_deployment_agent
    source: https://github.com/dfilppi/cloudify-oraclebmc-plugin/archive/0.1.zip
    package_name: cloudify-oraclebmc-plugin
    package_version: '0.1'

data_types:
  cloudify.datatypes.bmc.Config:
    properties:
      user:
        description: User OCID 
        type: string
        required: true
      fingerprint:
        description: API key fingerprint
        type: string
        required: true
      tenancy:
        description: Tenant OCID
        type: string
        required: true
      region:
        description: Region OCID
        type: string
        required: true
      key_file:
        description: the API private key
        type: string
        required: true
      log_requests:
        type: boolean
        required: true
        default: false
      pass_phrase:
        type: string
        required: true
        default: null
      additional_user_agent:
        type: string
        required: true
        default: ''

node_types:

  cloudify.oraclebmc.nodes.Instance:
    derived_from: cloudify.nodes.Compute
    properties:
      use_external_resource:
        description: >
          Indicate whether the resource exists or if Cloudify should create the resource,
          true if you are bringing an existing resource, false if you want cloudify to create it.
        type: boolean
        default: false
        required: true
      resource_id:
        description: >
          The OCID of the external resource, if use_external_resource is true.
          Otherwise it is null
        type: string
        required: false
      public_key_file:
        description: >
          Authorized SSH key for host
        type: string
        required: true
      name:
        description: >
          Optional field if you want to add a specific name to the instance.
        default: ''
        required: false
      image_id:
        description: >
          The OCID of the AMI image in your Amazon account.
        type: string
        required: true
      instance_shape:
        description: >
          The instance size/compute.  Shape OCID
        type: string
        required: true
      bmc_config:
        description: >
          A dictionary of values to pass to authenticate with the AWS API.
        type: cloudify.datatypes.bmc.Config
        required: false
      compartment_id:
        description: >
          The compartment OCID for the instance.  Required when not in managed context
        type: string
        required: false
      availability_domain:
        description: >
          The availability domain OCID.  Required when not in managed context
        type: string
        required: false
      subnet:
        description: >
                the subnet OCID to start the instance on.  Required when not in managed
                context
        type: string
        required: false
    interfaces:
      cloudify.interfaces.lifecycle:
        configure:
          implementation: bmc.bmc_compute.instance.launch_instance
        start:
          implementation: bmc.bmc_compute.instance.wait_for_running
          inputs:
            start_retry_interval:
              description: Polling interval until the server is active in seconds
              type: integer
              default: 10
        stop:
          implementation: bmc.bmc_compute.instance.terminate_instance
        delete:
          implementation: bmc.bmc_compute.instance.wait_for_terminated
          inputs:
            terminate_retry_interval:
              description: Polling interval until the server is terminated in seconds
              type: integer
              default: 10
#      cloudify.interfaces.validation:
#        creation:
#          implementation: bmc.ec2.instance.creation_validation
#
  cloudify.oraclebmc.nodes.VCN:
    derived_from: cloudify.nodes.Network
    properties:
      bmc_config:
        type: cloudify.datatypes.bmc.Config
        default: {}
        required: false
      resource_id:
        type: string
        required: false
      use_external_resource:
        type: boolean
        default: false
      name:
        description: >
          Optional field if you want to add a specific name to the instance.
        default: ''
      cidr_block:
        type: string
      compartment_id:
        type: string
      security_rules:
        description: list of string of format "<src-cidr>,<port>" (assumes tcp)
        default: []
    interfaces:
      cloudify.interfaces.lifecycle:
        start:
          implementation: bmc.bmc_network.network.create_vcn
        stop:
          implementation: bmc.bmc_network.network.delete_vcn
        delete:
          implementation: bmc.bmc_network.network.wait_for_vcn_terminated
          inputs:
            terminate_retry_interval:
              description: Polling interval until the network is terminated in seconds
              type: integer
              default: 10

  cloudify.oraclebmc.nodes.Subnet:
    derived_from: cloudify.nodes.Subnet
    properties:
      bmc_config:
        type: cloudify.datatypes.bmc.Config
        default: {}
      resource_id:
        type: string
        required: false
      use_external_resource:
        type: boolean
        default: false
      name:
        type: string
      cidr_block:
        type: string
      compartment_id:
        type: string
      availability_domain:
        type: string
    interfaces:
      cloudify.interfaces.lifecycle:
        start:
          implementation: bmc.bmc_network.network.create_subnet
        stop:
          implementation: bmc.bmc_network.network.delete_subnet
        delete:
          implementation: bmc.bmc_network.network.wait_for_subnet_terminated
          inputs:
            terminate_retry_interval:
              description: Polling interval until the subnet is terminated in seconds
              type: integer
              default: 10

  cloudify.oraclebmc.nodes.Gateway:
    derived_from: cloudify.nodes.Router
    properties:
      bmc_config:
        type: cloudify.datatypes.bmc.Config
        default: {}
      resource_id:
        type: string
        required: false
      use_external_resource:
        type: boolean
        default: false
      name:
        type: string
        default: ''
      compartment_id:
        type: string
      route_cidrs:
        default: []
      enabled:
        type: boolean
        default: true
    interfaces:
      cloudify.interfaces.lifecycle:
        start:
          implementation: bmc.bmc_network.network.create_gateway
        delete:
          implementation: bmc.bmc_network.network.delete_gateway

relationships:

  cloudify.oraclebmc.relationships.instance_connected_to_subnet:
    derived_from: cloudify.relationships.connected_to
    source_interfaces:
      cloudify.interfaces.relationship_lifecycle:
        preconfigure:
          implementation: bmc.bmc_network.network.connect_instance_to_subnet

  cloudify.oraclebmc.relationships.subnet_in_network:
    derived_from: cloudify.relationships.contained_in
    source_interfaces:
      cloudify.interfaces.relationship_lifecycle:
        postconfigure:
          implementation: bmc.bmc_network.network.connect_subnet_to_network

  cloudify.oraclebmc.relationships.gateway_connected_to_network:
    derived_from: cloudify.relationships.connected_to
    source_interfaces:
      cloudify.interfaces.relationship_lifecycle:
        postconfigure:
          implementation: bmc.bmc_network.network.connect_gateway_to_network
